version: "2"
linters:
  default: none
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - decorder
    - dupword
    - durationcheck
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - ginkgolinter
    - gocheckcompilerdirectives
    - gochecksumtype
    - goconst
    - gocritic
    - gocyclo
    - goheader
    - gosmopolitan
    - govet
    - grouper
    - importas
    - ineffassign
    - loggercheck
    - maintidx
    - makezero
    - mirror
    - misspell
    - musttag
    - nestif
    - nilerr
    - nilnil
    - nolintlint
    - nosprintfhostport
    - paralleltest
    - perfsprint
    - prealloc
    - predeclared
    - promlinter
    - protogetter
    - reassign
    - revive
    - rowserrcheck
    - sloglint
    - staticcheck
    - tagalign
    - testableexamples
    - testifylint
    - thelper
    - tparallel
    - unconvert
    - unused
    - usestdlibvars
    - wastedassign
    - whitespace
  settings:
    gosec:
      excludes:
        - G301
        - G302
        - G306
        - G601
        - G602
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
